import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import { Providers } from './providers/Providers'
import Header from './layout/Header'
import Footer from './layout/Footer'

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-montserrat'
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`antialiased ${montserrat.className}`}
        suppressHydrationWarning
      >
        <Providers>
          <Header />
          <div className="flex flex-col flex-1 min-h-0 p-2">
            <div className="mt-32 mb-32 flex-1 min-h-0">{children}</div>
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
